all tests passed
KrisBot2000/Secret-Number-Generator pull request #1
Opened 2017-06-15 23:48 UTC by KrisBot2000

2017-06-15 23:52 UTC, taesup requested changes

2017-06-15 23:52 UTC, taesup commented on secret_number.js
> +var genRandomNumber = Math.random();
This could be simplified. I don't think you need both sameRandomNumber and genRandomNumber.

2017-06-15 23:52 UTC, taesup commented on secret_number.js
> +  sameRandomNumber = genRandomNumber*1000001;
So at this point, genRandomNumber is Math.random() * 1000001 which at the highest is 1000000.99999 which is slightly above the limit of 1000000. Can you think of any other Math method that will allow you to hit 1000000 exactly?

2017-06-16 00:06 UTC, KrisBot2000 commented on secret_number.js
> +var genRandomNumber = Math.random();
fixed

2017-06-16 00:10 UTC, taesup commented on secret_number.js
> +var genRandomNumber = Math.random();
did you push your fix?

2017-06-16 00:19 UTC, taesup commented
Looks good! Free feel to merge into master.

![Thumbs Up](https://github.com/jglovier/gifs/blob/gh-pages/thumbs-up/thumbs-up.gif?raw=true)

2017-06-16 00:32 UTC, merged